test jq

diff --git a/.github/workflows/dist.yml b/.github/workflows/dist.yml
--- a/.github/workflows/dist.yml
+++ b/.github/workflows/dist.yml
@@ -1,47 +1,49 @@
-name: Dist CI
+name: update hints and dist
 
 on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
+  schedule:
+    - cron: '0 2 * * *'
   workflow_dispatch:
 
-
-defaults:
-  run:
-    shell: bash
-
 jobs:
-  dist-ci:
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - macos-latest
-          - ubuntu-latest
-          - windows-latest
-    runs-on: ${{ matrix.os }}
-
+  update:
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Run CI script
-        run: .ci/script.sh
-      - name: Apple Silicon Build
-        if: matrix.os == 'macos-latest'
+      - name: checkout
+        uses: actions/checkout@v3
+      - name: download new files
         run: |
-          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
-          sudo xcode-select -s /Applications/Xcode_12.4.app
-          CROSS_CI="aarch64-apple-darwin" .ci/script.sh
-      - name: iOS aarch64
-        if: matrix.os == 'macos-latest'
-        run: |
-          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
-          sudo xcode-select -s /Applications/Xcode_12.4.app
-          CROSS_CI="aarch64-apple-ios" .ci/script.sh
-      - name: iOS x64 simulator
-        if: matrix.os == 'macos-latest'
-        run: |
-          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
-          sudo xcode-select -s /Applications/Xcode_12.4.app
-          CROSS_CI="x86_64-apple-ios-simulator" .ci/script.sh
+          STATUS_SUCCEEDED=0 # from https://github.com/NixOS/hydra/blob/cf9f38e43fd81f9298e3f2ff50c8a6ee0acc3af0/hydra-api.yaml#L927-L941
+          baseUrl="https://everest-ci.paris.inria.fr"
+          latestFinishedEval=$(curl -sLH 'Content-Type: application/json' "$baseUrl/jobset/hacl-star/branch-master/latest-eval")
+          
+          rev=$(echo "$latestFinishedEval" | jq '.flake | split("/") | last')
+          id=$(echo "$latestFinishedEval" | jq '.id')
+          
+          [[ "$rev" == "$(git rev-parse HEAD)" ]] || {
+              echo "The latest evaluation on the CI doesn't correspond to the latest commit."
+              # exit 1 
+          }
+          
+          buildUrl="$baseUrl/eval/$id/job/hacl-build-products.x86_64-linux"
+          buildInfo=$(curl -sLH 'Content-Type: application/json' "$buildUrl")
+          
+          # Check wether the build was built correctly
+          [[ "$(echo "$buildInfo" | jq '.buildstatus')" == "$STATUS_SUCCEEDED" ]] || {
+              echo "The latest evaluation wasn't successful. Aborting."
+              exit 2
+          }
+          
+          installTar () {
+              curl -sL "$buildUrl/download-by-type/file/$1" | tar -xv
+          }
+          
+          installTar "hints"
+          installTar "dists"
+      - name: commit changes
+        uses: EndBug/add-and-commit@v9
+        with:
+          author_name: Project Everest
+          author_email: project@everest
+          message: "[CI] update hints and dist"
+          
